// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BigNest: typeof import('./src/components/BigNest.vue')['default']
    GameInfo: typeof import('./src/components/GameInfo.vue')['default']
    LoginCard: typeof import('./src/components/LoginCard.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallNest: typeof import('./src/components/SmallNest.vue')['default']
    SocialButton: typeof import('./src/components/SocialButton.vue')['default']
  }
}
